# Usa la imagen base oficial de NGINX
FROM nginx:1.25-alpine

# Argumento para el puerto (configurable en build time)
ARG NGINX_PORT_INTERNAL=80

# Copia el script para procesar las variables de entorno
COPY scripts/nginx/entrypoint.sh /entrypoint.sh

# Copia la plantilla de configuración de NGINX
COPY scripts/nginx/nginx.dev.conf /etc/nginx/templates/nginx.template.conf

# Asegura permisos de ejecución para el script
RUN chmod +x /entrypoint.sh

# Define el puerto que expondrá el contenedor (usando ARG)
EXPOSE $NGINX_PORT_INTERNAL

# Define el punto de entrada del contenedor
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]