# Imagen base
FROM python:3.12-slim

# Argumento para el puerto (configurable en build time)
ARG TASKS_API_PORT_INTERNAL=8020

# Crea un usuario no root
RUN useradd -m appuser

# Establecer directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY volumes/backend-tasks/requirements.txt .

# Actualiza pip a la última versión
RUN pip install --upgrade pip

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Cambia al usuario no root
USER appuser

# Puerto de la API de tareas (usando ARG)
EXPOSE $TASKS_API_PORT_INTERNAL

# Comando por defecto (usando variables de entorno)
CMD ["sh", "-c", "uvicorn main:app --host ${TASKS_API_HOST} --port ${TASKS_API_PORT_INTERNAL}"]