# Imagen base
FROM python:3.11-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY volumes/backend-worker/requirements.txt .

# Actualiza pip a la última versión
RUN pip install --upgrade pip

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Configurar el PYTHONPATH para permitir importaciones desde /app
ENV PYTHONPATH=/app

# Puerto de la API de tareas (tasks)
EXPOSE ${WORKER_API_PORT_INTERNAL}

# Ejecutar Celery como worker usando variables de entorno
CMD ["sh", "-c", "celery -A tasks worker --loglevel=${WORKER_LOG_LEVEL} --concurrency=${WORKER_CONCURRENCY} "]
