# Imagen base
FROM python:3.12-slim

# Crea un usuario no root
RUN useradd -m appuser

# Establecer directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY volumes/backend-worker/requirements.txt .

# Actualiza pip a la última versión
RUN pip install --upgrade pip

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Configurar el PYTHONPATH para permitir importaciones desde /app
ENV PYTHONPATH=/app

# Cambia al usuario no root
USER appuser

# Worker no necesita EXPOSE (no es una API, no expone puerto)

# Ejecutar Celery como worker usando variables de entorno
CMD ["sh", "-c", "celery -A tasks worker --loglevel=${WORKER_LOG_LEVEL} --concurrency=${WORKER_CONCURRENCY} --queues=${WORKER_QUEUES}"]