FROM python:3.12-slim

ARG EVENTS_ORCHESTRATOR_PORT_INTERNAL=8040

RUN useradd -m appuser

WORKDIR /app

COPY ./volumes/events-orchestrator/requirements.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

USER appuser

EXPOSE $EVENTS_ORCHESTRATOR_PORT_INTERNAL

CMD ["sh", "-c", "uvicorn main:app --host ${EVENTS_ORCHESTRATOR_HOST:-0.0.0.0} --port ${EVENTS_ORCHESTRATOR_PORT_INTERNAL:-8040} --reload"]
