import { ArrowRightLeft, TrendingUp, Box, Handshake, Users, Wallet } from 'lucide-react';

export const REPORT_GROUPS = [
  {
    id: 'sales',
    path: '/reports/sales',
    label: 'Reportes de ventas',
    moduleLabel: 'Módulo de Ventas',
    description:
      'Consulta, analiza y exporta información relacionada con las ventas registradas en las sucursales a las que tienes acceso.',
    Icon: TrendingUp,
    iconCls: 'text-blue-600 dark:text-blue-400',
    iconBg: 'bg-blue-50 dark:bg-blue-950/40',
    reports: [
      {
        id: 'daily-sales',
        label: 'Ventas diarias',
        description:
          'Permite analizar las ventas realizadas durante un rango de fechas determinado, filtrando la información por una, varias o todas las sucursales a las que el usuario tiene acceso.',
        type: 'Reporte operativo',
        path: '/reports/sales?report=daily-sales',
        available: true,
        tags: ['Rango de fechas', 'Filtro por sucursal', 'Exportación CSV', 'Exportación Excel', 'Reporte PDF'],
      },
      {
        id: 'returns-exchanges',
        label: 'Cambios y devoluciones',
        description:
          'Listado de documentos de cambio y devolución por rango de fechas, estado y locación, con crédito generado, artículos afectados y exportación CSV.',
        type: 'Reporte operativo',
        path: '/reports/sales?report=returns-exchanges',
        available: true,
        tags: ['Rango de fechas', 'Locación', 'Estado', 'Exportación CSV'],
      },
      {
        id: 'category-sales',
        label: 'Ventas por categoría',
        description: 'Desglose de ventas por categoría de producto, marca o familia en un período determinado. Identifica las categorías más rentables por sucursal.',
        type: 'Reporte gerencial',
        path: '/reports/sales?report=category-sales',
        available: true,
        tags: ['Categoría', 'Marca', 'Período', 'Sucursal', 'Reporte PDF'],
      },
      {
        id: 'customer-sales',
        label: 'Ventas por cliente',
        description: 'Ranking de clientes por monto de ventas en un período determinado. Muestra transacciones, ticket promedio y participación porcentual por cliente.',
        type: 'Reporte gerencial',
        path: '/reports/sales?report=customer-sales',
        available: true,
        tags: ['Cliente', 'RUT', 'Período', 'Sucursal', 'Reporte PDF'],
      },
      {
        id: 'seller-ranking',
        label: 'Ranking de vendedores',
        description: 'Clasificación de vendedores por monto de ventas, transacciones y ticket promedio en un período determinado.',
        type: 'Reporte gerencial',
        path: '/reports/sales?report=seller-ranking',
        available: true,
        tags: ['Vendedor', 'Período', 'Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'inventory',
    path: '/reports/inventory',
    label: 'Reportes de inventario',
    moduleLabel: 'Módulo de Inventario',
    description:
      'Consulta el estado del stock, movimientos y análisis de productos en las bodegas autorizadas.',
    Icon: Box,
    iconCls: 'text-emerald-600 dark:text-emerald-400',
    iconBg: 'bg-emerald-50 dark:bg-emerald-950/40',
    reports: [
      {
        id: 'stock',
        label: 'Stock general',
        description: 'Listado completo de productos con stock actual por bodega y totales consolidados.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Reporte PDF'],
      },
      {
        id: 'critical-stock',
        label: 'Stock crítico',
        description: 'Productos cuyo stock actual es igual o inferior al mínimo configurado.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Reporte PDF'],
      },
      {
        id: 'product-statement',
        label: 'Cartola de producto',
        description: 'Movimientos históricos de un producto con saldo actualizado por bodega.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Producto', 'Bodega', 'Período', 'Reporte PDF'],
      },
      {
        id: 'size-color-matrix',
        label: 'Matriz talla × color',
        description: 'Stock desglosado en cuadrícula por talla y color para análisis de variantes.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Producto', 'Reporte PDF'],
      },
      {
        id: 'product-movements',
        label: 'Movimientos por producto',
        description: 'Historial completo de entradas, salidas y ajustes de inventario por producto.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Producto', 'Período', 'Reporte PDF'],
      },
      {
        id: 'top-products',
        label: 'Ranking de productos',
        description: 'Productos más vendidos por cantidad, con comparativa interanual.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'transfers',
    path: '/reports/transfers',
    label: 'Reportes de transferencias',
    moduleLabel: 'Módulo de Transferencias',
    description:
      'Revisa el historial y estado de las transferencias de stock entre bodegas.',
    Icon: ArrowRightLeft,
    iconCls: 'text-violet-600 dark:text-violet-400',
    iconBg: 'bg-violet-50 dark:bg-violet-950/40',
    reports: [
      {
        id: 'transfers-list',
        label: 'Listado de transferencias',
        description: 'Historial de transferencias y ajustes entre bodegas por período seleccionado.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Período', 'Reporte PDF'],
      },
      {
        id: 'transfers-diff',
        label: 'Transferencias con diferencias',
        description: 'Transferencias que presentan discrepancias entre las cantidades enviadas y recibidas.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'petty-cash',
    path: '/reports/petty-cash',
    label: 'Reportes de caja chica',
    moduleLabel: 'Módulo de Caja Chica',
    description:
      'Consulta el detalle, resumen, saldos y reposiciones de fondos de caja chica por sucursal.',
    Icon: Wallet,
    iconCls: 'text-amber-600 dark:text-amber-400',
    iconBg: 'bg-amber-50 dark:bg-amber-950/40',
    reports: [
      {
        id: 'petty-cash-detail',
        label: 'Caja chica — detalle',
        description:
          'Gastos de caja chica por rango de fechas, sucursal y categoría. Incluye estado de aprobación y comprobante.',
        type: 'Reporte operativo',
        path: '/reports/petty-cash?report=petty-cash-detail',
        available: true,
        tags: [
          'Período',
          'Sucursal',
          'Categoría',
          'Estado',
          'Exportación CSV',
          'Reporte PDF',
        ],
      },
      {
        id: 'petty-cash-weekly',
        label: 'Caja chica — resumen semanal',
        description:
          'Consolidado semanal de gastos de caja chica agrupados por sucursal y categoría.',
        type: 'Reporte gerencial',
        path: '/reports/petty-cash?report=petty-cash-weekly',
        available: false,
        tags: ['Semana', 'Sucursal', 'Reporte PDF'],
      },
      {
        id: 'petty-cash-fund-status',
        label: 'Estado de fondos',
        description:
          'Saldo actual vs. saldo asignado de cada fondo de caja chica con nivel de agotamiento por sucursal.',
        type: 'Reporte operativo',
        path: '/reports/petty-cash?report=petty-cash-fund-status',
        available: false,
        tags: ['Sucursal', 'Responsable', 'Exportación CSV'],
      },
      {
        id: 'petty-cash-replenishments',
        label: 'Historial de reposiciones',
        description:
          'Reposiciones de fondos de caja chica solicitadas, aprobadas y rechazadas por período.',
        type: 'Reporte operativo',
        path: '/reports/petty-cash?report=petty-cash-replenishments',
        available: false,
        tags: ['Período', 'Sucursal', 'Estado', 'Exportación CSV'],
      },
      {
        id: 'petty-cash-by-category',
        label: 'Gastos por categoría',
        description:
          'Monto acumulado de gastos de caja chica agrupado por categoría en el período seleccionado.',
        type: 'Reporte gerencial',
        path: '/reports/petty-cash?report=petty-cash-by-category',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'cash-pos',
    path: '/reports/cash-pos',
    label: 'Reportes de caja POS',
    moduleLabel: 'Módulo de Caja POS',
    description:
      'Consulta aperturas, cierres, arqueos, movimientos extraordinarios y recaudación asociada a ventas POS.',
    Icon: Wallet,
    iconCls: 'text-emerald-600 dark:text-emerald-400',
    iconBg: 'bg-emerald-50 dark:bg-emerald-950/40',
    reports: [
      {
        id: 'cash-sessions',
        label: 'Historial de sesiones',
        description:
          'Aperturas y cierres de caja por cajero y sucursal con fondo inicial, fondo final y duración del turno.',
        type: 'Reporte operativo',
        path: '/reports/cash-pos?report=cash-sessions',
        available: false,
        tags: ['Período', 'Sucursal', 'Cajero', 'Exportación CSV'],
      },
      {
        id: 'cash-discrepancies',
        label: 'Diferencias de arqueo',
        description:
          'Sesiones de caja donde el monto contado difiere del monto esperado, ordenadas por diferencia.',
        type: 'Reporte gerencial',
        path: '/reports/cash-pos?report=cash-discrepancies',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF'],
      },
      {
        id: 'cash-extra-movements',
        label: 'Movimientos extraordinarios',
        description:
          'Ingresos y egresos de efectivo registrados durante sesiones de caja que no corresponden a ventas.',
        type: 'Reporte operativo',
        path: '/reports/cash-pos?report=cash-extra-movements',
        available: false,
        tags: ['Período', 'Sucursal', 'Tipo', 'Exportación CSV'],
      },
      {
        id: 'pos-collection-by-method',
        label: 'Recaudación por método de pago',
        description:
          'Desglose de lo cobrado en caja POS por método de pago: efectivo, débito, crédito y transferencia, por sucursal y período.',
        type: 'Reporte gerencial',
        path: '/reports/cash-pos?report=pos-collection-by-method',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF', 'Exportación CSV'],
      },
    ],
  },
  {
    id: 'customers',
    path: '/reports/customers',
    label: 'Reportes de clientes',
    moduleLabel: 'Módulo de Clientes',
    description:
      'Analiza el comportamiento y estado de cuenta de los clientes de tu negocio.',
    Icon: Users,
    iconCls: 'text-rose-600 dark:text-rose-400',
    iconBg: 'bg-rose-50 dark:bg-rose-950/40',
    reports: [
      {
        id: 'customer-ranking',
        label: 'Ranking de clientes',
        description: 'Clientes clasificados por monto de ventas con comparativa interanual.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Período', 'Reporte PDF'],
      },
      {
        id: 'accounts-receivable',
        label: 'Cuentas por cobrar',
        description: 'Estado de cuentas pendientes de cobro por cliente y sucursal.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'agreements',
    path: '/reports/agreements',
    label: 'Reportes de convenios',
    moduleLabel: 'Módulo de Convenios',
    description:
      'Analiza el estado, uso y beneficiarios de los convenios comerciales registrados.',
    Icon: Handshake,
    iconCls: 'text-teal-600 dark:text-teal-400',
    iconBg: 'bg-teal-50 dark:bg-teal-950/40',
    reports: [
      {
        id: 'agreement-summary',
        label: 'Resumen de convenios',
        description: 'Vista consolidada de todos los convenios con monto comprometido, consumido y porcentaje de uso.',
        type: 'Reporte operativo',
        path: '/reports/agreements?report=agreement-summary',
        available: true,
        tags: ['Filtro por tipo', 'Filtro por estado', 'Exportación CSV'],
      },
      {
        id: 'agreement-usage',
        label: 'Uso de convenios',
        description: 'Historial de transacciones que aplicaron un convenio, con detalle de beneficiario y monto utilizado.',
        type: 'Reporte operativo',
        path: '/reports/agreements?report=agreement-usage',
        available: true,
        tags: ['Filtro por convenio', 'Exportación CSV'],
      },
      {
        id: 'agreement-beneficiaries',
        label: 'Beneficiarios por convenio',
        description: 'Lista de beneficiarios de un convenio con su estado y cantidad de usos registrados.',
        type: 'Reporte operativo',
        path: '/reports/agreements?report=agreement-beneficiaries',
        available: true,
        tags: ['Selector de convenio', 'Filtro por estado', 'Exportación CSV'],
      },
      {
        id: 'agreement-validity',
        label: 'Vigencia de convenios',
        description: 'Estado de vigencia de todos los convenios: activos, próximos a vencer (≤30 días) y vencidos.',
        type: 'Reporte gerencial',
        path: '/reports/agreements?report=agreement-validity',
        available: true,
        tags: ['Agrupado por vigencia', 'Exportación CSV'],
      },
    ],
  },
];
