import { ArrowRightLeft, TrendingUp, Box, Handshake, Users, Wallet } from 'lucide-react';

export const REPORT_GROUPS = [
  {
    id: 'sales',
    path: '/reports/sales',
    label: 'Reportes de ventas',
    moduleLabel: 'Módulo de Ventas',
    description:
      'Consulta, analiza y exporta información relacionada con las ventas registradas en las sucursales a las que tienes acceso.',
    Icon: TrendingUp,
    iconCls: 'text-blue-600 dark:text-blue-400',
    iconBg: 'bg-blue-50 dark:bg-blue-950/40',
    reports: [
      {
        id: 'daily-sales',
        label: 'Ventas diarias',
        description:
          'Permite analizar las ventas realizadas durante un rango de fechas determinado, filtrando la información por una, varias o todas las sucursales a las que el usuario tiene acceso.',
        type: 'Reporte operativo',
        path: '/reports/sales?report=daily-sales',
        available: true,
        tags: ['Rango de fechas', 'Filtro por sucursal', 'Exportación CSV', 'Exportación Excel', 'Reporte PDF'],
      },
      {
        id: 'monthly-summary',
        label: 'Resumen mensual',
        description: 'Consolidado de ventas del mes con resumen diario y comparativa respecto al mes anterior.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Mes', 'Sucursal', 'Reporte PDF'],
      },
      {
        id: 'customer-sales',
        label: 'Ventas por cliente',
        description: 'Historial anual de ventas por cliente con desglose mensual y totales acumulados.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Cliente', 'Período', 'Reporte PDF'],
      },
      {
        id: 'seller-ranking',
        label: 'Ranking de vendedores',
        description: 'Clasificación de vendedores por monto y cantidad de transacciones en el período.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'inventory',
    path: '/reports/inventory',
    label: 'Reportes de inventario',
    moduleLabel: 'Módulo de Inventario',
    description:
      'Consulta el estado del stock, movimientos y análisis de productos en las bodegas autorizadas.',
    Icon: Box,
    iconCls: 'text-emerald-600 dark:text-emerald-400',
    iconBg: 'bg-emerald-50 dark:bg-emerald-950/40',
    reports: [
      {
        id: 'stock',
        label: 'Stock general',
        description: 'Listado completo de productos con stock actual por bodega y totales consolidados.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Reporte PDF'],
      },
      {
        id: 'critical-stock',
        label: 'Stock crítico',
        description: 'Productos cuyo stock actual es igual o inferior al mínimo configurado.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Reporte PDF'],
      },
      {
        id: 'product-statement',
        label: 'Cartola de producto',
        description: 'Movimientos históricos de un producto con saldo actualizado por bodega.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Producto', 'Bodega', 'Período', 'Reporte PDF'],
      },
      {
        id: 'size-color-matrix',
        label: 'Matriz talla × color',
        description: 'Stock desglosado en cuadrícula por talla y color para análisis de variantes.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Producto', 'Reporte PDF'],
      },
      {
        id: 'product-movements',
        label: 'Movimientos por producto',
        description: 'Historial completo de entradas, salidas y ajustes de inventario por producto.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Producto', 'Período', 'Reporte PDF'],
      },
      {
        id: 'top-products',
        label: 'Ranking de productos',
        description: 'Productos más vendidos por cantidad, con comparativa interanual.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'transfers',
    path: '/reports/transfers',
    label: 'Reportes de transferencias',
    moduleLabel: 'Módulo de Transferencias',
    description:
      'Revisa el historial y estado de las transferencias de stock entre bodegas.',
    Icon: ArrowRightLeft,
    iconCls: 'text-violet-600 dark:text-violet-400',
    iconBg: 'bg-violet-50 dark:bg-violet-950/40',
    reports: [
      {
        id: 'transfers-list',
        label: 'Listado de transferencias',
        description: 'Historial de transferencias y ajustes entre bodegas por período seleccionado.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Período', 'Reporte PDF'],
      },
      {
        id: 'transfers-diff',
        label: 'Transferencias con diferencias',
        description: 'Transferencias que presentan discrepancias entre las cantidades enviadas y recibidas.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Bodega', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'cash',
    path: '/reports/cash',
    label: 'Reportes de caja',
    moduleLabel: 'Módulo de Caja',
    description:
      'Consulta el detalle y resumen de los movimientos de caja chica en tus sucursales.',
    Icon: Wallet,
    iconCls: 'text-amber-600 dark:text-amber-400',
    iconBg: 'bg-amber-50 dark:bg-amber-950/40',
    reports: [
      {
        id: 'petty-cash-detail',
        label: 'Caja chica — detalle',
        description: 'Gastos de caja chica por rango de fechas, sucursal y categoría de gasto.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Período', 'Sucursal', 'Reporte PDF'],
      },
      {
        id: 'petty-cash-weekly',
        label: 'Caja chica — resumen semanal',
        description: 'Consolidado semanal de gastos de caja chica agrupados por sucursal.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Semana', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'customers',
    path: '/reports/customers',
    label: 'Reportes de clientes',
    moduleLabel: 'Módulo de Clientes',
    description:
      'Analiza el comportamiento y estado de cuenta de los clientes de tu negocio.',
    Icon: Users,
    iconCls: 'text-rose-600 dark:text-rose-400',
    iconBg: 'bg-rose-50 dark:bg-rose-950/40',
    reports: [
      {
        id: 'customer-ranking',
        label: 'Ranking de clientes',
        description: 'Clientes clasificados por monto de ventas con comparativa interanual.',
        type: 'Reporte gerencial',
        available: false,
        tags: ['Período', 'Reporte PDF'],
      },
      {
        id: 'accounts-receivable',
        label: 'Cuentas por cobrar',
        description: 'Estado de cuentas pendientes de cobro por cliente y sucursal.',
        type: 'Reporte operativo',
        available: false,
        tags: ['Sucursal', 'Reporte PDF'],
      },
    ],
  },
  {
    id: 'agreements',
    path: '/reports/agreements',
    label: 'Reportes de convenios',
    moduleLabel: 'Módulo de Convenios',
    description:
      'Analiza el estado, uso y beneficiarios de los convenios comerciales registrados.',
    Icon: Handshake,
    iconCls: 'text-teal-600 dark:text-teal-400',
    iconBg: 'bg-teal-50 dark:bg-teal-950/40',
    reports: [
      {
        id: 'agreement-summary',
        label: 'Resumen de convenios',
        description: 'Vista consolidada de todos los convenios con monto comprometido, consumido y porcentaje de uso.',
        type: 'Reporte operativo',
        path: '/reports/agreements?report=agreement-summary',
        available: true,
        tags: ['Filtro por tipo', 'Filtro por estado', 'Exportación CSV'],
      },
      {
        id: 'agreement-usage',
        label: 'Uso de convenios',
        description: 'Historial de transacciones que aplicaron un convenio, con detalle de beneficiario y monto utilizado.',
        type: 'Reporte operativo',
        path: '/reports/agreements?report=agreement-usage',
        available: true,
        tags: ['Filtro por convenio', 'Exportación CSV'],
      },
      {
        id: 'agreement-beneficiaries',
        label: 'Beneficiarios por convenio',
        description: 'Lista de beneficiarios de un convenio con su estado y cantidad de usos registrados.',
        type: 'Reporte operativo',
        path: '/reports/agreements?report=agreement-beneficiaries',
        available: true,
        tags: ['Selector de convenio', 'Filtro por estado', 'Exportación CSV'],
      },
      {
        id: 'agreement-validity',
        label: 'Vigencia de convenios',
        description: 'Estado de vigencia de todos los convenios: activos, próximos a vencer (≤30 días) y vencidos.',
        type: 'Reporte gerencial',
        path: '/reports/agreements?report=agreement-validity',
        available: true,
        tags: ['Agrupado por vigencia', 'Exportación CSV'],
      },
    ],
  },
];
