// ====================================
// volumes/frontend/src/pages/admin/users/mockData.js
// Datos de prueba para la página de administración de usuarios
// ====================================

// Datos estadísticos mock
export const mockStats = {
  totalUsers: 25,
  activeUsers: 22,
  inactiveUsers: 3,
  newUsersThisMonth: 4,
  lastLoginToday: 18,
  adminUsers: 2,
  managerUsers: 4,
  regularUsers: 19
};

// Usuarios mock con datos realistas
export const mockUsers = [
  {
    id: 1,
    username: "admin.demo",
    email: "admin@inventario.local",
    fullName: "Administrador Sistema",
    firstName: "Administrador",
    lastName: "Sistema",
    phone: "+56912345678",
    isActive: true,
    roles: ["Administrador"],
    rolesCodes: ["ADMIN"],
    permissions: ["USERS_MANAGE", "ROLES_MANAGE", "SYSTEM_CONFIG", "ALL_PERMISSIONS"],
    warehouses: ["Todas las bodegas"],
    warehouseAccess: ["TIENDA_CENTRO", "TIENDA_MALL", "BODEGA_CENTRAL", "TIENDA_VALPO"],
    avatar: null,
    initials: "AS",
    lastLogin: "2025-08-18T10:30:00Z",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2025-08-18T10:30:00Z",
    profileCompleteness: 100,
    securityScore: 95,
    status: "online",
    department: "Administración",
    position: "Administrador de Sistema"
  },
  {
    id: 2,
    username: "jefe.bodega",
    email: "jefe.bodega@inventario.local",
    fullName: "Carlos Mendoza",
    firstName: "Carlos",
    lastName: "Mendoza",
    phone: "+56987654321",
    isActive: true,
    roles: ["Jefe de Bodega"],
    rolesCodes: ["WAREHOUSE_MANAGER"],
    permissions: ["INVENTORY_MANAGE", "PRODUCTS_MANAGE", "WAREHOUSE_MANAGE"],
    warehouses: ["Bodega Central"],
    warehouseAccess: ["BODEGA_CENTRAL"],
    avatar: null,
    initials: "CM",
    lastLogin: "2025-08-18T09:15:00Z",
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2025-08-18T09:15:00Z",
    profileCompleteness: 85,
    securityScore: 88,
    status: "online",
    department: "Operaciones",
    position: "Jefe de Bodega"
  },
  {
    id: 3,
    username: "vendedor.centro",
    email: "vendedor.centro@inventario.local",
    fullName: "María González",
    firstName: "María",
    lastName: "González",
    phone: "+56955512345",
    isActive: true,
    roles: ["Vendedor"],
    rolesCodes: ["SALES_PERSON"],
    permissions: ["SALES_CREATE", "PRODUCTS_VIEW", "INVENTORY_VIEW"],
    warehouses: ["Tienda Centro"],
    warehouseAccess: ["TIENDA_CENTRO"],
    avatar: null,
    initials: "MG",
    lastLogin: "2025-08-18T11:00:00Z",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2025-08-18T11:00:00Z",
    profileCompleteness: 90,
    securityScore: 82,
    status: "online",
    department: "Ventas",
    position: "Vendedor Senior"
  },
  {
    id: 4,
    username: "vendedor.mall",
    email: "vendedor.mall@inventario.local",
    fullName: "Pedro Ramírez",
    firstName: "Pedro",
    lastName: "Ramírez",
    phone: "+56933445566",
    isActive: true,
    roles: ["Vendedor"],
    rolesCodes: ["SALES_PERSON"],
    permissions: ["SALES_CREATE", "PRODUCTS_VIEW", "INVENTORY_VIEW"],
    warehouses: ["Tienda Mall"],
    warehouseAccess: ["TIENDA_MALL"],
    avatar: null,
    initials: "PR",
    lastLogin: "2025-08-18T08:45:00Z",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2025-08-18T08:45:00Z",
    profileCompleteness: 75,
    securityScore: 79,
    status: "online",
    department: "Ventas",
    position: "Vendedor"
  },
  {
    id: 5,
    username: "cajero.demo",
    email: "cajero@inventario.local",
    fullName: "Ana López",
    firstName: "Ana",
    lastName: "López",
    phone: "+56977889900",
    isActive: true,
    roles: ["Cajero"],
    rolesCodes: ["CASHIER"],
    permissions: ["CASH_OPERATIONS", "SALES_VIEW"],
    warehouses: ["Tienda Centro"],
    warehouseAccess: ["TIENDA_CENTRO"],
    avatar: null,
    initials: "AL",
    lastLogin: "2025-08-17T18:30:00Z",
    createdAt: "2024-04-05T00:00:00Z",
    updatedAt: "2025-08-17T18:30:00Z",
    profileCompleteness: 70,
    securityScore: 75,
    status: "offline",
    department: "Ventas",
    position: "Cajero"
  },
  {
    id: 6,
    username: "supervisor.demo",
    email: "supervisor@inventario.local",
    fullName: "Roberto Silva",
    firstName: "Roberto",
    lastName: "Silva",
    phone: "+56911223344",
    isActive: true,
    roles: ["Supervisor"],
    rolesCodes: ["SUPERVISOR"],
    permissions: ["TEAM_MANAGE", "REPORTS_VIEW", "INVENTORY_MANAGE"],
    warehouses: ["Tienda Centro", "Tienda Mall"],
    warehouseAccess: ["TIENDA_CENTRO", "TIENDA_MALL"],
    avatar: null,
    initials: "RS",
    lastLogin: "2025-08-18T07:20:00Z",
    createdAt: "2024-01-30T00:00:00Z",
    updatedAt: "2025-08-18T07:20:00Z",
    profileCompleteness: 95,
    securityScore: 91,
    status: "away",
    department: "Operaciones",
    position: "Supervisor de Tienda"
  },
  {
    id: 7,
    username: "consultor.demo",
    email: "consultor@inventario.local",
    fullName: "Laura Martínez",
    firstName: "Laura",
    lastName: "Martínez",
    phone: "+56944556677",
    isActive: true,
    roles: ["Consultor"],
    rolesCodes: ["VIEWER"],
    permissions: ["REPORTS_VIEW", "PRODUCTS_VIEW"],
    warehouses: ["Solo lectura"],
    warehouseAccess: [],
    avatar: null,
    initials: "LM",
    lastLogin: "2025-08-16T16:45:00Z",
    createdAt: "2024-05-12T00:00:00Z",
    updatedAt: "2025-08-16T16:45:00Z",
    profileCompleteness: 60,
    securityScore: 70,
    status: "offline",
    department: "Consultoría",
    position: "Analista"
  },
  {
    id: 8,
    username: "contador.demo",
    email: "contador@inventario.local",
    fullName: "Jorge Herrera",
    firstName: "Jorge",
    lastName: "Herrera",
    phone: "+56966778899",
    isActive: true,
    roles: ["Contador"],
    rolesCodes: ["ACCOUNTANT"],
    permissions: ["REPORTS_VIEW", "FINANCIAL_VIEW", "AUDIT_VIEW"],
    warehouses: ["Acceso financiero"],
    warehouseAccess: ["TIENDA_CENTRO", "TIENDA_MALL", "BODEGA_CENTRAL"],
    avatar: null,
    initials: "JH",
    lastLogin: "2025-08-18T09:00:00Z",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2025-08-18T09:00:00Z",
    profileCompleteness: 88,
    securityScore: 85,
    status: "online",
    department: "Finanzas",
    position: "Contador General"
  },
  {
    id: 9,
    username: "nuevo.usuario",
    email: "nuevo@inventario.local",
    fullName: "Carmen Vega",
    firstName: "Carmen",
    lastName: "Vega",
    phone: "+56922334455",
    isActive: false,
    roles: ["Vendedor"],
    rolesCodes: ["SALES_PERSON"],
    permissions: ["SALES_CREATE", "PRODUCTS_VIEW"],
    warehouses: ["Sin asignar"],
    warehouseAccess: [],
    avatar: null,
    initials: "CV",
    lastLogin: null,
    createdAt: "2025-08-15T00:00:00Z",
    updatedAt: "2025-08-15T00:00:00Z",
    profileCompleteness: 30,
    securityScore: 45,
    status: "inactive",
    department: "Ventas",
    position: "Vendedor Trainee"
  },
  {
    id: 10,
    username: "temp.user",
    email: "temporal@inventario.local",
    fullName: "Usuario Temporal",
    firstName: "Usuario",
    lastName: "Temporal",
    phone: null,
    isActive: false,
    roles: ["Consultor"],
    rolesCodes: ["VIEWER"],
    permissions: ["PRODUCTS_VIEW"],
    warehouses: ["Solo lectura"],
    warehouseAccess: [],
    avatar: null,
    initials: "UT",
    lastLogin: "2025-08-10T14:20:00Z",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2025-08-12T00:00:00Z",
    profileCompleteness: 25,
    securityScore: 40,
    status: "inactive",
    department: "Temporal",
    position: "Acceso Temporal"
  }
];

// Opciones para filtros
export const mockFilterOptions = {
  roles: [
    { value: "", label: "Todos los roles" },
    { value: "ADMIN", label: "Administrador" },
    { value: "WAREHOUSE_MANAGER", label: "Jefe de Bodega" },
    { value: "SUPERVISOR", label: "Supervisor" },
    { value: "SALES_PERSON", label: "Vendedor" },
    { value: "CASHIER", label: "Cajero" },
    { value: "ACCOUNTANT", label: "Contador" },
    { value: "VIEWER", label: "Consultor" }
  ],

  status: [
    { value: "", label: "Todos los estados" },
    { value: "active", label: "Activos" },
    { value: "inactive", label: "Inactivos" }
  ],

  warehouses: [
    { value: "", label: "Todas las bodegas" },
    { value: "TIENDA_CENTRO", label: "Tienda Centro" },
    { value: "TIENDA_MALL", label: "Tienda Mall" },
    { value: "BODEGA_CENTRAL", label: "Bodega Central" },
    { value: "TIENDA_VALPO", label: "Tienda Valparaíso" }
  ],

  departments: [
    { value: "", label: "Todos los departamentos" },
    { value: "Administración", label: "Administración" },
    { value: "Operaciones", label: "Operaciones" },
    { value: "Ventas", label: "Ventas" },
    { value: "Finanzas", label: "Finanzas" },
    { value: "Consultoría", label: "Consultoría" }
  ]
};

// Datos para el modal de usuario
export const mockUserFormData = {
  roles: mockFilterOptions.roles.filter(role => role.value !== ""),
  warehouses: mockFilterOptions.warehouses.filter(warehouse => warehouse.value !== ""),
  departments: mockFilterOptions.departments.filter(dept => dept.value !== ""),

  permissions: [
    { code: "USERS_MANAGE", name: "Gestionar Usuarios" },
    { code: "ROLES_MANAGE", name: "Gestionar Roles" },
    { code: "SYSTEM_CONFIG", name: "Configurar Sistema" },
    { code: "INVENTORY_MANAGE", name: "Gestionar Inventario" },
    { code: "PRODUCTS_MANAGE", name: "Gestionar Productos" },
    { code: "WAREHOUSE_MANAGE", name: "Gestionar Bodegas" },
    { code: "SALES_CREATE", name: "Crear Ventas" },
    { code: "SALES_VIEW", name: "Ver Ventas" },
    { code: "CASH_OPERATIONS", name: "Operaciones de Caja" },
    { code: "REPORTS_VIEW", name: "Ver Reportes" },
    { code: "FINANCIAL_VIEW", name: "Ver Información Financiera" },
    { code: "AUDIT_VIEW", name: "Ver Auditoría" },
    { code: "TEAM_MANAGE", name: "Gestionar Equipo" },
    { code: "PRODUCTS_VIEW", name: "Ver Productos" },
    { code: "INVENTORY_VIEW", name: "Ver Inventario" }
  ]
};

// Configuración de paginación
export const mockPagination = {
  currentPage: 1,
  totalPages: 2,
  totalItems: 10,
  itemsPerPage: 10,
  itemsPerPageOptions: [5, 10, 25, 50, 100]
};