CREATE TABLE IF NOT EXISTS `sale_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sale_code` varchar(36) NOT NULL,
  `status` enum('PENDING_CASHIER','CLOSED','CANCELLED') NOT NULL DEFAULT 'PENDING_CASHIER',
  `document_type_code` varchar(30) NOT NULL DEFAULT 'TICKET',
  `document_type_name` varchar(100) NOT NULL DEFAULT 'Ticket de venta',
  `ticket_number` varchar(60) DEFAULT NULL,
  `warehouse_id` bigint(20) unsigned DEFAULT NULL,
  `sales_point_id` bigint(20) unsigned DEFAULT NULL,
  `cash_register_id` bigint(20) unsigned DEFAULT NULL,
  `payment_method_code` varchar(20) DEFAULT NULL,
  `payment_method_name` varchar(100) DEFAULT NULL,
  `amount_tendered` decimal(14, 2) DEFAULT NULL,
  `change_amount` decimal(14, 2) DEFAULT NULL,
  `customer_id` bigint(20) unsigned DEFAULT NULL,
  `customer_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`customer_snapshot`)),
  `authorized_buyer_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`authorized_buyer_snapshot`)),
  `prepared_by_user_id` bigint(20) unsigned DEFAULT NULL,
  `closed_by_user_id` bigint(20) unsigned DEFAULT NULL,
  `prepared_by_name` varchar(150) DEFAULT NULL,
  `subtotal_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `line_discount_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `document_discount_type` varchar(20) NOT NULL DEFAULT 'NONE',
  `document_discount_value` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `document_discount_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sale_documents_sale_code` (`sale_code`),
  UNIQUE KEY `uk_sale_documents_ticket_number` (`ticket_number`),
  KEY `idx_sale_documents_sale_code` (`sale_code`),
  KEY `idx_sale_documents_status` (`status`),
  KEY `idx_sale_documents_ticket_number` (`ticket_number`),
  KEY `idx_sale_documents_warehouse_id` (`warehouse_id`),
  KEY `idx_sale_documents_sales_point_id` (`sales_point_id`),
  KEY `idx_sale_documents_cash_register_id` (`cash_register_id`),
  KEY `idx_sale_documents_customer_id` (`customer_id`),
  KEY `idx_sale_documents_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_sale_documents_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`),
  CONSTRAINT `fk_sale_documents_sales_point` FOREIGN KEY (`sales_point_id`) REFERENCES `sales_points` (`id`),
  CONSTRAINT `fk_sale_documents_cash_register` FOREIGN KEY (`cash_register_id`) REFERENCES `cash_registers` (`id`),
  CONSTRAINT `fk_sale_documents_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `fk_sale_documents_prepared_by` FOREIGN KEY (`prepared_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_sale_documents_closed_by` FOREIGN KEY (`closed_by_user_id`) REFERENCES `users` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `sale_document_lines` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sale_document_id` bigint(20) unsigned NOT NULL,
  `line_number` int(11) NOT NULL,
  `product_id` bigint(20) unsigned DEFAULT NULL,
  `product_variant_id` bigint(20) unsigned DEFAULT NULL,
  `product_code` varchar(100) DEFAULT NULL,
  `product_name` varchar(255) NOT NULL,
  `unit_name` varchar(80) DEFAULT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `unit_price` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `discount_percent` decimal(7, 4) NOT NULL DEFAULT 0.0000,
  `line_subtotal` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `line_discount_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `document_discount_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `paid_total_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sale_line_number` (`sale_document_id`, `line_number`),
  KEY `idx_sale_document_lines_sale_document_id` (`sale_document_id`),
  KEY `idx_sale_document_lines_product_id` (`product_id`),
  KEY `idx_sale_document_lines_product_variant_id` (`product_variant_id`),
  KEY `idx_sale_document_lines_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_sale_document_lines_sale_document` FOREIGN KEY (`sale_document_id`) REFERENCES `sale_documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sale_document_lines_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `fk_sale_document_lines_product_variant` FOREIGN KEY (`product_variant_id`) REFERENCES `product_variants` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `sale_line_units` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sale_document_id` bigint(20) unsigned NOT NULL,
  `sale_document_line_id` bigint(20) unsigned NOT NULL,
  `unit_sequence` int(11) NOT NULL,
  `paid_amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `status` enum('SOLD','RETURNED','EXCHANGED') NOT NULL DEFAULT 'SOLD',
  `return_reference` varchar(60) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sale_line_unit_sequence` (`sale_document_line_id`, `unit_sequence`),
  KEY `idx_sale_line_units_sale_document_id` (`sale_document_id`),
  KEY `idx_sale_line_units_sale_document_line_id` (`sale_document_line_id`),
  KEY `idx_sale_line_units_status` (`status`),
  KEY `idx_sale_line_units_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_sale_line_units_sale_document` FOREIGN KEY (`sale_document_id`) REFERENCES `sale_documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sale_line_units_line` FOREIGN KEY (`sale_document_line_id`) REFERENCES `sale_document_lines` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `sale_returns` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sale_document_id` bigint(20) unsigned NOT NULL,
  `sale_line_unit_id` bigint(20) unsigned NOT NULL,
  `action_type` varchar(20) NOT NULL,
  `amount` decimal(15, 2) NOT NULL DEFAULT 0.00,
  `reason` varchar(255) DEFAULT NULL,
  `created_by_user_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sale_returns_sale_document_id` (`sale_document_id`),
  KEY `idx_sale_returns_sale_line_unit_id` (`sale_line_unit_id`),
  KEY `idx_sale_returns_created_by_user_id` (`created_by_user_id`),
  KEY `idx_sale_returns_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_sale_returns_sale_document` FOREIGN KEY (`sale_document_id`) REFERENCES `sale_documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sale_returns_sale_line_unit` FOREIGN KEY (`sale_line_unit_id`) REFERENCES `sale_line_units` (`id`),
  CONSTRAINT `fk_sale_returns_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
