CREATE TABLE IF NOT EXISTS user_session_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(255) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  login_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  logout_at TIMESTAMP NULL DEFAULT NULL,
  last_seen_at TIMESTAMP NULL DEFAULT NULL,
  login_method VARCHAR(40) NULL,
  logout_method VARCHAR(40) NULL,
  ip_address VARCHAR(45) NULL,
  user_agent TEXT NULL,
  browser_name VARCHAR(80) NULL,
  browser_version VARCHAR(80) NULL,
  os_name VARCHAR(80) NULL,
  device_type VARCHAR(40) NULL,
  client_timezone VARCHAR(80) NULL,
  client_language VARCHAR(120) NULL,
  client_platform VARCHAR(120) NULL,
  client_vendor VARCHAR(120) NULL,
  hardware_concurrency INT UNSIGNED NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_session_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uk_user_session_history_session (session_id),
  INDEX idx_user_session_history_user_login (user_id, login_at),
  INDEX idx_user_session_history_active (user_id, is_active),
  INDEX idx_user_session_history_ip (ip_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
